token:
  expiration_time: 86400000
  secret: '{cypher}AQBWfQXPSh35FWnq4U4Tj9AZAdrXO+lGTPHalcWBPl155sUUNXz5f+pA2GXt5MZx8O/bD94xyl6uCTWrS08Df+nd8vTiSOsurvh/ORPLI2TRsmGiMucFfgpl2j6KDEKKt6JBrSE0wH9IpJV8tbjKiPNXBhXAWsywu490PACEI8HXoOh4/E/ickJj3MYKqXIQOjYn0KJGjLR+TOOERC5LVfBtz2A21PIyBEZXu741MBl5naGhzI8Fxdoe8cTdxOzpdUwm5+PYZ8XPnKAjcFque2LgGhyMPnoLMAkjSZJ/MkQ24HmS5kaEGQaQ9T85xHX5XHyHFubpvmhJnlNgArZnCTGk7Fc5/2+XIbgKBQQylZGepNhD8DPmpQJzQRqSb+XPhciOSVE8CzV9UmFEr96dWGWA'
